const stateCodeMap = {
 IN:{ name:"India"},
  AN: { code: "35", name: "Andaman and Nicobar Islands" },
  AP: { code: "37", name: "Andhra Pradesh" },
  AR: { code: "12", name: "Arunachal Pradesh" },
  AS: { code: "18", name: "Assam" },
  BR: { code: "10", name: "Bihar" },
  CH: { code: "04", name: "Chandigarh" },
  CT: { code: "22", name: "Chhattisgarh" },
  DL: { code: "07", name: "Delhi" },
  DN: { code: "26", name: "Dadra and Nagar Haveli and Daman and Diu" },
  GA: { code: "30", name: "Goa" },
  GJ: { code: "24", name: "Gujarat" },
  HR: { code: "06", name: "Haryana" },
  HP: { code: "02", name: "Himachal Pradesh" },
  JK: { code: "01", name: "Jammu and Kashmir" },
  JH: { code: "20", name: "Jharkhand" },
  KA: { code: "29", name: "Karnataka" },
  KL: { code: "32", name: "Kerala" },
  LA: { code: "38", name: "Ladakh" },
  LD: { code: "31", name: "Lakshadweep" },
  MH: { code: "27", name: "Maharashtra" },
  ML: { code: "17", name: "Meghalaya" },
  MN: { code: "14", name: "Manipur" },
  MP: { code: "23", name: "Madhya Pradesh" },
  MZ: { code: "15", name: "Mizoram" },
  NL: { code: "13", name: "Nagaland" },
  OD: { code: "21", name: "Odisha" },
  PB: { code: "03", name: "Punjab" },
  PY: { code: "34", name: "Puducherry" },
  RJ: { code: "08", name: "Rajasthan" },
  SK: { code: "11", name: "Sikkim" },
  TN: { code: "33", name: "Tamil Nadu" },
  TS: { code: "36", name: "Telangana" },
  TR: { code: "16", name: "Tripura" },
  UP: { code: "09", name: "Uttar Pradesh" },
  UK: { code: "05", name: "Uttarakhand" },
  WB: { code: "19", name: "West Bengal" },
  DNHDD: { code: "26", name: "Dadra and Nagar Haveli and Daman and Diu" },
  DH: { code: "26", name: "Dadra and Nagar Haveli and Daman and Diu" },
  DD: { code: "26", name: "Dadra and Nagar Haveli and Daman and Diu" },
};

module.exports = stateCodeMap;
